#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
  path: /login_check

register:
  path: /register
  controller: App\UserBundle\Controller\AuthenticationController::RegisterUserAction

